### ISSUE TITLE
Append to PR description instead

### ISSUE THREAD

**Issue by skirpichev** [manics/action-binderbadge#154]
Or have an option for this.  Ex. to avoid Github notifications.

**Comment by manics** [comment]
Sounds like a good idea! Do you have any thoughts on how action should check for an existing comment to update? Should it just look for a string that matches
https://github.com/manics/action-binderbadge/blob/d9f227cf7902bf9d6c755735dcc12669cf0a431d/src/binder.ts#L40
Or do you think it should also check for a prefix/suffix/blank-lines/line etc to reduce the chance of it modifying a user's description?

**Comment by skirpichev** [comment]
@manics, thanks.  This mostly works.

Yet, the pr description still updated after new commits even with persistentLink=false.  My action:
```
$ cat .github/workflows/binder-badge.yml 
name: binder-badge
on:
  pull_request_target:
jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: manics/action-binderbadge@d7fc6853e6b1944335d7a280059e5556e7b6bf0e
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          environmentRepo: gh/diofant/mybinder-env/HEAD
          urlpath: lab/tree/test.ipynb
          updateDescription: true
          persistentLink: false
```

**Comment by manics** [comment]
It was working for me .... let me take another look

**Comment by skirpichev** [comment]
Here is a [pr](https://github.com/skirpichev/sandbox/pull/2) with the problem.

**Comment by manics** [comment]
Currently this action only checks for exact duplicate comments, and appends a new "comment" if different, I thought that was safer (and easier!) than trying to modify an existing comment.

It looks like your two URLs are different:
`https://mybinder.org/v2/gh/diofant/mybinder-env/HEAD?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fskirpichev%252Fsandbox%26branch%3Dpr2%26urlpath%3Dtest.ipynb`
`https://mybinder.org/v2/gh/diofant/mybinder-env/HEAD?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fskirpichev%252Fsandbox%26branch%3Dpr2%26urlpath%3Dlab%252Ftree%252Ftest.ipynb`

Did you change `urlpath: test.ipynb` to `urlpath: lab/tree/test.ipynb`?

**Comment by skirpichev** [comment]
Yeah, I're right.  Sorry for the noise.  Thank you.
