### ISSUE TITLE
Support different repo for the binder environment configs

### ISSUE THREAD

**Issue by skirpichev** [manics/action-binderbadge#301]
See [docs](https://mybinder.readthedocs.io/en/latest/howto/external_binder_setup.html).

**Comment by manics** [comment]
Hi! Do you want to use this action with a different content repository, or a different environment?

**Comment by skirpichev** [comment]
With a different repository for required Binder setup files (e.g. for runtime.txt and so on).

**Comment by manics** [comment]
If you're still interested please give the main branch a try!

**Comment by skirpichev** [comment]
Thanks, I'll try.

**Comment by skirpichev** [comment]
Hmm, @manics, not sure how to specify github repo (e.g. https://github.com/diofant/mybinder-env).  Is this supported, or only gist's?

**Comment by manics** [comment]
Try `environmentRepo: gh/diofant/mybinder-env/HEAD`. It's whatever comes after `https://mybinder.org/v2/` in a normal mybinder link (e.g.`https://mybinder.org/v2/gh/diofant/mybinder-env/HEAD`) so any repo type supported by mybinder should work.

**Comment by skirpichev** [comment]
Hmm, without persistent links this is not so useful:(  Perhaps, I should ask nbgitpuller team to add support for this?  Or, better - you?

**Comment by manics** [comment]
Please could you open an issue on https://github.com/jupyterhub/nbgitpuller ? It's always better for the use-case to be described by the user!

**Comment by skirpichev** [comment]
https://github.com/jupyterhub/nbgitpuller/issues/239
