### ISSUE TITLE
Node.js depreceted - 2023-09-22-github-actions-transitioning-from-node-16-to-node-20

### ISSUE THREAD

**Issue by acpennlab** [manics/action-binderbadge#677]
Hi there, 

I just tried creating a GitHub action using `action-binderbadge` but the action fails with the following error: 

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: manics/action-binderbadge@main. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

The advice to upgrade is described in the links below:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

Is this simply as simple as changing 'node16' to 'node20' in line 28 of action.yml?

Best

Andy

**Comment by manics** [comment]
Thanks for the report! I'm trying to update all dependencies as well as the node version but it'll require more work: https://github.com/manics/action-binderbadge/pull/678

**Comment by manics** [comment]
Fixed in `main`, and also `v3.0.0`
